id: I1732789A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:59:50+00:00'
last_modified: '2022-06-08T10:24:23.000890+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7886
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་ཀྱི་རྩ་འགྲེལ་གཅེས་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4A2A:
      image_group_id: I3CN7888
      title: ''
      total_pages: 778
      order: 1
      base_file: 4A2A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
