id: P009352
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN7886
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་ཀྱི་རྩ་འགྲེལ་གཅེས་བཏུས།
  author: ''
  volumes:
    7811b73abe124db9939ec7d107c33e0f:
      image_group_id: I3CN7888
      title: ''
      volume_number: 1
      total_pages: 778
      base_file: v001.txt
